[helpers]

[default]
depends = []

[default.files]
"nvim" = "~/.config/nvim"
"foot" = "~/.config/foot"
"kitty" = "~/.config/kitty"
"niri" = "~/.config/niri"
"swaylock" = "~/.config/swaylock"
"fuzzel" = "~/.config/fuzzel"

[default.variables]

[settings]
default_target_type = "automatic"
