[helpers]

[default]
depends = []

[default.files]
"nvim" = "~/.config/nvim"
"foot" = "~/.config/foot"
"kitty" = "~/.config/kitty"
"niri" = "~/.config/niri"
"swaylock" = "~/.config/swaylock"
"fuzzel" = "~/.config/fuzzel"
"tmux" = "~/.config/tmux"
"fastfetch" = "~/.config/fastfetch"
"wlogout" = "~/.config/wlogout"
"udiskie" = "~/.config/udiskie"
"waybar" = "~/.config/waybar"
#"fish" = "~/.config/fish"
"git" = "~/.config/git"

[default.variables]

[settings]
default_target_type = "automatic"
