[main]
font=JetBrainsMono Nerd Font Mono:size=20
terminal=foot
dpi-aware=no
minimal-lines=true

# Nord theme
[colors]
background=2e3440ff
text=d8dee9ff
match=88c0d0ff
selection=434c5eff
selection-text=e5e9f0ff
selection-match=88c0d0ff
border=4c566aff
