[symlinks]
"fastfetch/config.jsonc" = "/home/aved/.config/fastfetch/config.jsonc"
"fish/config.fish" = "/home/aved/.config/fish/config.fish"
"foot/foot.ini" = "/home/aved/.config/foot/foot.ini"
"fuzzel/fuzzel.ini" = "/home/aved/.config/fuzzel/fuzzel.ini"
"git/config" = "/home/aved/.config/git/config"
"kitty/kitty.conf" = "/home/aved/.config/kitty/kitty.conf"
"niri/config.kdl" = "/home/aved/.config/niri/config.kdl"
"nvim/init.lua" = "/home/aved/.config/nvim/init.lua"
"nvim/lua/plugins.lua" = "/home/aved/.config/nvim/lua/plugins.lua"
"swaylock/config" = "/home/aved/.config/swaylock/config"
"tmux/tmux.conf" = "/home/aved/.config/tmux/tmux.conf"
"udiskie/config.yml" = "/home/aved/.config/udiskie/config.yml"
vimrc = "/home/aved/.vimrc"
"waybar/config" = "/home/aved/.config/waybar/config"
"waybar/style.css" = "/home/aved/.config/waybar/style.css"
"wlogout/layout" = "/home/aved/.config/wlogout/layout"

[templates]
